__title__ = 'Onlyfans-scraper'
__version__ = 'v0.4'
__author__ = 'Ghost6446'
__author_email__ = ''
__description__ = 'A command-line program to download media, posts, and more from OnlyFans'
__url__ = 'https://github.com/Ghost6446/Onlyfans-scrapper'
__license__ = 'MIT License'
__copyright__ = 'Copyright 2023'